@startuml

actor Tutor

Tutor -> persons : get person by name
persons -> course: if person != null
Tutor -> course : addStudentByName(studentName)
    course -> students : add(studentName) \nto ArrayList<Student>

@enduml