@startuml

actor Tutor
collections Courses

Tutor -> Courses : get course
Tutor -> course : getRankByName(studentName)
    course -> toplist : firstOrNull(studentName)
toplist -> Tutor: rank value as Double

@enduml

@startuml

actor Student

Student ->toplistRepo: get Rank by name
Student ->toplistRepo: get(student's rank)
toplistRepo ->Rank: get particular rank as double
Rank ->Student: return a double between 0 and 1


@enduml