@startuml

actor Tutor
collections Courses

Tutor -> Courses : get course
Tutor -> course : readGrades(studentName)
loop 
    course -> task : getTask(taskName)
    task -> grade: getGrade(studentName)
    course -> grade : get person max value
end
course -> Tutor : grade value

@enduml