@startuml

actor Admin
collections Courses

Admin -> Courses : get course by name
Courses -> course: if courses[courseName] = null
activate course
Admin -> course : addCourse(courseName)
deactivate course
course -> Courses: add to ArrayList<Course>

@enduml