@startuml

actor Admin
collections Courses

Admin -> Courses : get course by name
Courses -> course: if course already exists \nit can't be added
activate course
Admin -> course : addCourse(courseName)
deactivate course
course -> Courses: add to array

@enduml