@startuml setTask
actor Tutor

collections Courses

Tutor -> Courses : get course
Tutor -> Course : add(taskName, taskType)
Course -> Task : << create >>
activate Task
deactivate Task
Task -> Course  : add to ArrayList<Task>
@enduml